export PYTHONPATH="${PWD}/agent"

export PORT=8830

export HOME_PATH="${PWD}"

export POSTGRES_USER="YOUR_PS_USER"
export POSTGRES_PASSWORD="YOUR_PS_PASSWORD"
export POSTGRES_DB="YOUR_PS_DB"

export ANTHROPIC_KEY_NAME="PUT-YOUR-KEY-NAME"
export ANTHROPIC_API_KEY="PUT-YOUR-KEY_HERE"

export VENV=myenv